name: Flutter

on:
  push:
    branches:
      - main # Trigger when a commit is pushed to the android-build branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the build process

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Set up the Flutter environment
        with:
          flutter-version: '3.35.1'  # Specify the Flutter version

      - name: Flutter pub get
        run: flutter pub get  # Install Flutter dependencies

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/bullvest.jks  # Correct path for the keystore

      - name: Set permissions on gradlew
        run: chmod +x android/gradlew  # Make gradlew executable

      - name: Build APK and AAB
        working-directory: android  # Set working directory to android folder
        run: |
          ./gradlew clean assembleRelease bundleRelease  # Build the APK and AAB
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}  # Pass keystore password
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}  # Pass the key alias
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}  # Pass the key password

      - name: Upload APK and AAB
        uses: actions/upload-artifact@v4  # Upload APK and AAB as artifacts
        with:
          name: flutter-android-artifacts
          path: |
            android/app/build/outputs/flutter-apk/*.apk
            android/app/build/outputs/bundle/release/*.aab

      - name: 📤 Upload APK and AAB via uppy.sh
        run: |
          for file in \
            android/app/build/outputs/flutter-apk/app-release.apk \
            android/app/build/outputs/bundle/release/app-release.aab; do
            if [ -f "$file" ]; then
              echo "📤 Uploading $file ..."
              url=$(curl --upload-file "$file" "https://uppy.sh/$(basename "$file")")
              echo "  Uploaded: $url"
            else
              echo "  Not found: $file"
            fi
          done
